version: '3.5'

services:

 web_dev:
  build: .
  ports:
   - "8080:80"
  volumes:
   - .:/app
  environment:
   - DB=mongodb://mongodb:27017

 mongodb:
  image: mongo:latest
  environment:
   - MONGO_DATA_DIR=/usr/data/db
   - MONGO_LOG_DIR=/dev/null
  volumes:
   - ./data/db:/usr/data/db
  ports:
   - 27017:27017
  command: mongod --logpath=/dev/null # --quiet

networks:
 default:
