[workspace]
members = [
  "hello_world",
]

[workspace.metadata.raze]
genmode = "Remote"
rust_rules_workspace_name = "rules_rust"
targets = [
  "x86_64-apple-darwin",
  "x86_64-pc-windows-msvc",
  "x86_64-unknown-linux-gnu",
]
workspace_path = "//cargo"
